db = "/app/strfry-db"

relay {
    bind = "0.0.0.0"
    port = 7777
    nofiles = 0
    realIpHeader = "x-forwarded-for"

    info {
        name = "RelayPress"
        description = "RelayPress private editorial relay"
        pubkey = ""
        contact = ""
        icon = ""
        nips = ""
    }
}
